services:
  drission-cloud-driver:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      CLOAK_BASE_URL: "http://cloak-browser-manager:3000"
      TZ: Asia/Shanghai
    volumes:
      - ../configs:/app/configs
